name: Sync GitHub Files

on:
  schedule:
    - cron: '0 */6 * * *'  # æ¯6å°æ—¶ä¸€æ¬¡
  workflow_dispatch:
  
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Download files
        run: |
          rm -f sub sub2
          curl -s https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub -o sub
          curl -s https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub -o sub2
          echo "æ–‡ä»¶ä¸‹è½½å®Œæˆ!"
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'ğŸ”„ Auto-sync files'
          add: '*'
