name: Sync GitHub Files

on:
  schedule:
    - cron: '0 */6 * * *'  # æ¯6å°æ—¶ä¸€æ¬¡
  workflow_dispatch:
  
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download files
        run: |
          rm -f sub sub2 *.m3u
          curl -s https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub -o sub
          curl -s https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub -o sub2
          curl -s https://raw.githubusercontent.com/mytv-android/China-TV-Live-M3U8/refs/heads/main/iptv.m3u -o iptv.m3u
          curl -s https://raw.githubusercontent.com/ckmah74/iptv/refs/heads/main/IPTV2025 -o iptv_2025.m3u
          curl -s https://github.com/ghokun/tv/blob/main/bin/playlist.m3u -o tv.m3u
          echo "æ–‡ä»¶ä¸‹è½½å®Œæˆ!"
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'ğŸ”„ Auto-sync files'
          add: '*'
